title: Max's Projects
description: Builds and things I've learned along the way.
url: "https://greystoke1337.github.io"
baseurl: "/blog"
theme: minima

author:
  name: Max

header_pages:
  - about.md

exclude:
  - editor.html
  - CLAUDE.md
  - README.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
